[[main]]
  name = "Inicio"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Investigación"
  pageRef = "/investigacion"
  weight = 20

[[main]]
  name = "Notas"
  pageRef = "/notas"
  weight = 30

[[main]]
  name = "Sentipensares"
  pageRef = "/sentipensares"
  weight = 40

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 20

[[social]]
  name = "Medium"
  pre = "fab medium"
  url = "https://medium.com/"
  weight = 30

# toml-docs-start sample-navigation
[[sample]]
  name = "Inicio"
  pageRef = "/"
  weight = 10

[[sample]]
  name = "Investigación"
  pageRef = "/investigacion"
  weight = 20

[[sample]]
  name = "Notas"
  pageRef = "/notas"
  weight = 30

[[sample]]
  name = "Sentipensares"
  pageRef = "/sentipensares"
  weight = 40
# toml-docs-end sample-navigation