[[main]]
  name = "Inicio"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Descolonizando"
  pageRef = "/descolonizando/"
  weight = 20

[[main]]
  name = "Galería"
  pageRef = "/galeria"
  weight = 30

[[social]]
  name = "Instagram"
  pre = "fab fa-instagram"
  url = "https://www.instagram.com/furiosasresistencias/"
  weight = 10

[[social]]
  name = "Facebook"
  pre = "fab fa-facebook"
  url = "https://www.instagram.com/furiosasresistencias/"
  weight = 20

[[social]]
  name = "Twitter"
  pre = "fab fa-twitter"
  url = "https://www.x.com/FResistencias"
  weight = 30

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/FuriosasResistencias"
  weight = 40

# toml-docs-start sample-navigation
[[sample]]
  name = "Inicio"
  pageRef = "/"
  weight = 10

[[sample]]
  name = "Investigación"
  pageRef = "/investigacion"
  weight = 20

[[sample]]
  name = "Notas"
  pageRef = "/notas"
  weight = 30

[[sample]]
  name = "Sentipensares"
  pageRef = "/sentipensares"
  weight = 40
# toml-docs-end sample-navigation